name: CI


on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release-wasm:
        type: boolean
        default: false
      release-models:
        type: boolean
        default: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
          cache: pip
          cache-dependency-path: requirements.frozen.txt
      
      - name: Build
        run: |
          mkdir cpp/build
          cd cpp/build
          cmake ..
          make
      
      - name: pytest
        run: |
          pip install \
            --index-url https://download.pytorch.org/whl/cpu \
            --extra-index-url https://pypi.org/simple        \
            -r requirements.frozen.txt
          ./run_tests.sh
      
  
  models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
          cache: pip
          cache-dependency-path: requirements.frozen.txt

      - name: fetch-from-huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir models
          cd models
          git clone https://user:${HF_TOKEN}@huggingface.co/carrot-qwa/angiosperm-treerings
          cd angiosperm-treerings
          git checkout release-candidate
          ls -halt
          # only one modelfile
          python -c "import glob; assert len(glob.glob('./*.pt.zip')) == 1"

      - name: pip-install
        run: |
          pip install \
            --index-url https://download.pytorch.org/whl/cpu \
            --extra-index-url https://pypi.org/simple        \
            -r ./requirements.frozen.txt

      - name: export
        run: |
          cd models/angiosperm-treerings
          MODELFILE=$(realpath ./*.pt.zip)
          echo $MODELFILE
          python ../../update-yolo.py --model=$MODELFILE
          
          CARROTFILE=$(realpath ./*.carrot.pt.zip)
          ONNXFILE=$(realpath ./*.onnx)
          echo $CARROTFILE
          echo $ONNXFILE

          # running twice to make sure the hash is deterministic
          # NOTE: file name is important, therefore copying to a new folder
          mkdir COPY && cd COPY
          cp $MODELFILE ./
          python ../../../update-yolo.py --model ./*.pt.zip

          ls -halt

          sha256sum ../*.carrot.pt.zip ./*.carrot.pt.zip
          test "$(sha256sum $CARROTFILE | cut -d' ' -f1)" = \
              "$(sha256sum ./*.carrot.pt.zip | cut -d' ' -f1)"

          sha256sum ../*.onnx ./*.onnx
          test "$(sha256sum $ONNXFILE | cut -d' ' -f1)" = \
              "$(sha256sum ./*.onnx | cut -d' ' -f1)"

          cd ..
          rm -r COPY

          echo "CARROTFILE=${CARROTFILE}" >> "$GITHUB_ENV"
          echo "ONNXFILE=${ONNXFILE}" >> "$GITHUB_ENV"
      

      - name: Archive Models
        uses: actions/upload-artifact@v7
        with:
          name: models
          path: |
            ${{ env.CARROTFILE }}
            ${{ env.ONNXFILE }}
          if-no-files-found: error


      - name: Release
        if: ${{ github.event.inputs.release-models == 'true' }}
        run: |
          cd models/angiosperm-treerings
          git checkout main
          git config user.email carrot-qwa@users.noreply.huggingface.co
          git config user.name carrot-qwa
          git add ${{env.CARROTFILE}}
          git add ${{env.ONNXFILE}}
          if ! git diff --cached --quiet; then
              TAGNAME=v$(date +%F)
              echo $TAGNAME
              git commit -m "$TAGNAME"
              git tag --force $TAGNAME
              git push origin main
              git push origin --tags
          else
            echo "No changes"
          fi




          # TODO:
          # run tests with this model
          # compute hashsum of evaluation code
          # fetch/git clone evaluation set from huggingface
          # compute hashsum of dataset
          # if all 3 hashes have not changed, skip
          # run inference
          # run postprocessing
          # run evaluation
          # evaluation artifcacts
            # metadata: 3 hashes
            # metrics json
            # per-image pixel-wise error maps
          # model artifacts



  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.69
          actions-cache-folder: 'emsdk-cache'

      - name: Deno
        run: |
          ./deno.sh task cache
      
      - name: Build
        run: |
          emcc -v
          mkdir cpp/build-wasm
          cd cpp/build-wasm
          emcmake cmake ..                      \
            -DCMAKE_BUILD_TYPE=Release          \
            -DCMAKE_VERBOSE_MAKEFILE=ON
          emmake make
          ../../deno.sh bundle --minify --outdir=./bundle ../carrot-wasm-postprocessing.ts

      - name: Test
        run: |
          ./run_tests_deno.sh
      
      - name: Archive JS module
        uses: actions/upload-artifact@v7
        with:
          name: modules
          path: |
            cpp/build-wasm/bundle/carrot-wasm-postprocessing.js
            cpp/carrot-wasm-postprocessing.d.ts
          if-no-files-found: error

  release-wasm:
    needs:   build-wasm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.inputs.release-wasm == 'true' }}

    steps:
      - uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: modules
          path: artifact/

      - name: Release
        run: |
          TAGNAME=v$(date +%F)
          echo $TAGNAME

          git fetch origin wasm-releases
          git checkout wasm-releases
          cp artifact/carrot-wasm-postprocessing.d.ts ./
          cp artifact/build-wasm/bundle/carrot-wasm-postprocessing.js ./
          rm -r artifact
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./carrot-wasm-postprocessing.*
          git commit -m "$TAGNAME"
          git tag --force $TAGNAME
          git push origin wasm-releases
          git push origin --tags


